apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: hotdesk
data:
  MYSQL_DATABASE: "hot"
  MYSQL_USER: "root"
  init-db.sql: |
    -- Create database
    CREATE DATABASE IF NOT EXISTS hot;
    USE hot;

    -- Create rooms table first (referenced by other tables)
    CREATE TABLE IF NOT EXISTS `rooms` (
      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `room_name` varchar(255) NOT NULL,
      `desk_total` int(11) DEFAULT NULL,
      `created_at` timestamp NULL DEFAULT current_timestamp(),
      `updated_at` timestamp NULL DEFAULT NULL,
      `room_image` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Create users table
    CREATE TABLE IF NOT EXISTS `users` (
      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `name` varchar(255) DEFAULT NULL,
      `username` varchar(255) NOT NULL,
      `username_verified_at` timestamp NULL DEFAULT current_timestamp(),
      `password` varchar(255) NOT NULL,
      `two_factor_secret` text DEFAULT NULL,
      `two_factor_recovery_codes` text DEFAULT NULL,
      `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
      `remember_token` varchar(100) DEFAULT NULL,
      `current_team_id` bigint(20) unsigned DEFAULT NULL,
      `profile_photo_path` varchar(2048) DEFAULT NULL,
      `created_at` timestamp NULL DEFAULT current_timestamp(),
      `updated_at` timestamp NULL DEFAULT NULL,
      `guid` varchar(255) DEFAULT NULL,
      `domain` varchar(255) DEFAULT NULL,
      `is_admin` tinyint(1) DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `users_username_unique` (`username`),
      UNIQUE KEY `users_guid_unique` (`guid`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Create bookings table
    CREATE TABLE IF NOT EXISTS `bookings` (
      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `user_id` bigint(20) unsigned DEFAULT NULL,
      `desk_id` bigint(20) unsigned DEFAULT NULL,
      `room_id` bigint(20) DEFAULT NULL,
      `res_date` bigint(20) DEFAULT NULL,
      `updated_at` timestamp NULL DEFAULT NULL,
      `created_at` timestamp NULL DEFAULT current_timestamp(),
      `user_name` varchar(255) DEFAULT NULL,
      UNIQUE KEY `bookings_id_idx` (`id`) USING BTREE,
      KEY `bookings_user_id_foreign` (`user_id`),
      KEY `bookings_desk_id` (`desk_id`),
      CONSTRAINT `bookings_user_id_foreign` FOREIGN KEY (`user_id`)
      REFERENCES `users` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB AUTO_INCREMENT=325 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Create images table
    CREATE TABLE IF NOT EXISTS `images` (
      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `room_id` bigint(20) unsigned DEFAULT NULL,
      `image_path` varchar(255) DEFAULT NULL,
      UNIQUE KEY `images_id_idx` (`id`) USING BTREE,
      KEY `images_room_id_foreign` (`room_id`) USING BTREE,
      CONSTRAINT `images_ibfk_1` FOREIGN KEY (`room_id`)
      REFERENCES `rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Create settings table
    CREATE TABLE IF NOT EXISTS `settings` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `setting_key` varchar(255) NOT NULL,
      `setting_value` text,
      `setting_type` enum('string','integer','float','boolean','json') DEFAULT 'string',
      `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
      `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`),
      UNIQUE KEY `setting_key` (`setting_key`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Insert admin user 
    INSERT INTO users (name, username, password, is_admin) VALUES 
    ('admin', 'admin', '$2a$12$vq3.hepxaniJ99ghV4Q0/.fNsULWh.0dBSfuovxkHxCr1HQtOHmma', 1)
    ON DUPLICATE KEY UPDATE password = VALUES(password);

    -- Insert default LDAP settings
    INSERT INTO `settings` (`setting_key`, `setting_value`, `setting_type`) VALUES 
    ('ldap_enabled', '0', 'boolean'),
    ('ldap_host', 'ldapserver.ad.contoso.co.uk', 'string'),
    ('ldap_port', '389', 'integer'),
    ('ldap_base_dn', 'DC=ad,DC=contoso,DC=co,DC=uk', 'string'),
    ('ldap_user_dn', 'OU=FIN,OU=PS,OU=Accounts,DC=ad,DC=contoso,DC=co,DC=uk', 'string'),
    ('ldap_use_ssl', '0', 'boolean'),
    ('ldap_use_tls', '0', 'boolean'),
    ('ldap_protocol', 'ldap://', 'string'),
    ('ldap_version', '3', 'integer'),
    ('ldap_timeout', '5', 'integer'),
    ('ldap_follow_referrals', '0', 'boolean')
    ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);

    -- Insert first room
    INSERT INTO rooms (room_name) VALUES ('...') 
    ON DUPLICATE KEY UPDATE room_name = VALUES(room_name);
