apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: hotdesk
  labels:
    app: php-fpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: 192.168.1.211:5000/project-php-fpm:latest  # Build and push your custom image
        ports:
        - containerPort: 9000
        env:
        - name: PHP_MEMORY_LIMIT
          valueFrom:
            configMapKeyRef:
              name: php-fpm-config
              key: PHP_MEMORY_LIMIT
        - name: PHP_UPLOAD_MAX_FILESIZE
          valueFrom:
            configMapKeyRef:
              name: php-fpm-config
              key: PHP_UPLOAD_MAX_FILESIZE
        - name: PHP_POST_MAX_SIZE
          valueFrom:
            configMapKeyRef:
              name: php-fpm-config
              key: PHP_POST_MAX_SIZE
        - name: PHP_MAX_EXECUTION_TIME
          valueFrom:
            configMapKeyRef:
              name: php-fpm-config
              key: PHP_MAX_EXECUTION_TIME
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-code
        persistentVolumeClaim:
          claimName: app-code-pvc
